FROM ubuntu:24.04

RUN apt-get update && apt-get install -y wget fuse libfuse2 file squashfs-tools build-essential
RUN wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x /appimagetool-x86_64.AppImage

WORKDIR /workspace
RUN /appimagetool-x86_64.AppImage AppDir